name: deploy-prd
on:
  workflow_dispatch:
    inputs:
      deploy-version:
        description: 'Version to deploy'
        required: true
jobs:
  deploy-prd:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ github.event.inputs.deploy-version }}
      - name: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: k8s
          location: asia-southeast1-a
          credentials: ${{ secrets.GKE_CREDENTIALS }}
      - name: deploy
        uses: deliverybot/helm@v1
        with:
          helm: helm3
          release: bookinfo-prd-ratings
          namespace: student34-bookinfo-prd
          chart: k8s/helm
          value-files: k8s/helm-values/values-bookinfo-prd-ratings.yaml
          values: |
            {
              "ratings": {
                "tag": "${{ github.event.inputs.deploy-version }}"
              },
              "extraEnv": {
                "COMMIT_SHA": "${{ github.sha }}"
              }
            }